name: image_hasher_dart
description: Package allowing creation of image hash that can be used to compare images for physical similarity.
version: 2.0.0
repository: https://github.com/KopaczPatryk/image_hasher_dart

environment:
  sdk: ^3.1.3

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  bit_array: ^2.2.1
  bitcount: ^0.3.0
  equatable: ^2.0.5
  image: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^4.0.0
  test: ^1.21.0
